spring.application.name=passgen

# CORS - Permitir apenas os Frontends locais
cors.allowed-origins=http://localhost:5173,http://localhost:3000

# URLs do Swagger para o painel de documentação
swagger.server.url.local=http://localhost:8080
swagger.server.url.prod=https://passgen-api.onrender.com

# Swagger Ativado em Desenvolvimento
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Actuator (Métricas de saúde)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never