spring.application.name=passgen
cors.allowed-origins=http://localhost:5173,http://localhost:3000

# Desenvolvimento
swagger.server.url.local=http://localhost:8080
# swagger.server.url.prod=https://passgen-api.onrender.com

# Desabilita o Swagger em produção (opcional mas recomendado)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never