# CORS - Permitir apenas o Frontend publicado na Vercel
cors.allowed-origins=https://passgen.vercel.app

# Desabilita o Swagger em produção por segurança
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false